In [2]:
pip install scikit-learn

Collecting scikit-learn
  Using cached scikit_learn-1.8.0-cp311-cp311-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.24.1 in c:\Users\HP\Desktop\Saas-Churn\.venv\Lib\site-packages (from scikit-learn) (2.4.6)
Collecting scipy>=1.10.0 (from scikit-learn)
  Using cached scipy-1.17.1-cp311-cp311-win_amd64.whl.metadata (60 kB)
Collecting joblib>=1.3.0 (from scikit-learn)
  Using cached joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting threadpoolctl>=3.2.0 (from scikit-learn)
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Using cached scikit_learn-1.8.0-cp311-cp311-win_amd64.whl (8.1 MB)
Using cached joblib-1.5.3-py3-none-any.whl (309 kB)
Using cached scipy-1.17.1-cp311-cp311-win_amd64.whl (36.6 MB)
Using cached threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, scipy, joblib, scikit-learn

   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   -------------------- ------------------- 2/4 [joblib]
   -------------------- ------------------- 2/4 [joblib]
   -------------------- ------------------- 2/4 [joblib]
   -------------------- ------------------- 2/4 [joblib]
   -------------------- ------------------- 2/4 [joblib]
   -------------------- ------------------- 2/4 [joblib]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ---------------------------------------- 4/4 [scikit-learn]

Successfully installed joblib-1.5.3 scikit-learn-1.8.0 scipy-1.17.1 threadpoolctl-3.6.0
Note: you may need to restart the kernel to use updated packages.

In [3]:
import pandas as pd
import numpy as np
import sqlite3

from sklearn.preprocessing import (
    StandardScaler,
    OneHotEncoder
)

pd.set_option("display.max_columns", None)

In [4]:
conn = sqlite3.connect(
    "../../data/warehouse/saas.db"
)

In [5]:
df = pd.read_sql_query(
    "SELECT * FROM customer_360",
    conn
)

df.head()

,user_id,country,industry,company_size,plan_type,monthly_revenue,is_churned,total_usage_events,avg_session_duration,total_tickets,avg_resolution_time,avg_satisfaction,total_campaign_engagements,email_open_rate,click_rate
0,1,USA,SaaS,Enterprise,Pro,150,0,54,33.648148,0,NaN,NaN,15,0.666667,0.533333
1,2,India,Healthcare,Small,Basic,50,1,7,4.714286,3,69.333333,4.333333,2,0.000000,0.500000
2,3,UK,SaaS,Enterprise,Basic,50,1,13,5.230769,6,60.833333,3.666667,1,1.000000,0.000000
3,4,Canada,SaaS,Enterprise,Basic,50,0,99,34.747475,0,NaN,NaN,8,0.750000,0.750000
4,5,Germany,SaaS,Small,Basic,50,0,117,33.512821,4,16.250000,7.250000,11,0.545455,0.545455

In [6]:
df["customer_health_score"] = (
    df["avg_session_duration"] * 0.4
    + df["email_open_rate"] * 30
    + df["click_rate"] * 30
    - df["total_tickets"] * 2
)

In [7]:
session_duration * 0.4

NameError: name 'session_duration' is not defined

In [8]:
df["avg_session_duration"] * 0.4

0       13.459259
1        1.885714
2        2.092308
3       13.898990
4       13.405128
          ...
4995    13.796721
4996    13.890526
4997    14.255319
4998    13.277966
4999    12.766667
Name: avg_session_duration, Length: 5000, dtype: float64

In [10]:
df["customer_health_score"] = (
    df["avg_session_duration"] * 0.4
    + df["email_open_rate"] * 30
    + df["click_rate"] * 30
    - df["total_tickets"] * 2
)

In [11]:
df["engagement_score"] = (
    df["total_usage_events"] * 0.5
    + df["avg_session_duration"] * 2
)

In [12]:
df[[
    "total_usage_events",
    "avg_session_duration",
    "engagement_score"
]].head()

   total_usage_events  avg_session_duration  engagement_score
0                  54             33.648148         94.296296
1                   7              4.714286         12.928571
2                  13              5.230769         16.961538
3                  99             34.747475        118.994949
4                 117             33.512821        125.525641

In [13]:
df["support_burden_score"] = (
    df["total_tickets"] * 3
    + (
        10 - df["avg_satisfaction"].fillna(10)
    ) * 2
)

In [15]:
df[[
    "total_tickets",
    "avg_satisfaction",
    "support_burden_score"
]].head()

   total_tickets  avg_satisfaction  support_burden_score
0              0               NaN              0.000000
1              3          4.333333             20.333333
2              6          3.666667             30.666667
3              0               NaN              0.000000
4              4          7.250000             17.500000

In [16]:
df["marketing_engagement_score"] = (
    df["email_open_rate"] * 50
    + df["click_rate"] * 50
)

In [17]:
df[[
    "email_open_rate",
    "click_rate",
    "marketing_engagement_score"
]].head()

   email_open_rate  click_rate  marketing_engagement_score
0         0.666667    0.533333                   60.000000
1         0.000000    0.500000                   25.000000
2         1.000000    0.000000                   50.000000
3         0.750000    0.750000                   75.000000
4         0.545455    0.545455                   54.545455

In [18]:
df["frequency_score"] = (
    df["total_usage_events"]
)

In [19]:
df["monetary_score"] = (
    df["monthly_revenue"]
)

In [20]:
df["recency_score"] = np.random.randint(
    1,
    30,
    size=len(df)
)

In [21]:
df.isnull().sum()

user_id                         0
country                         0
industry                        0
company_size                    0
plan_type                       0
monthly_revenue                 0
is_churned                      0
total_usage_events              0
avg_session_duration            0
total_tickets                   0
avg_resolution_time           727
avg_satisfaction              727
total_campaign_engagements      0
email_open_rate                 0
click_rate                      0
customer_health_score           0
engagement_score                0
support_burden_score            0
marketing_engagement_score      0
frequency_score                 0
monetary_score                  0
recency_score                   0
dtype: int64

In [22]:
df["avg_resolution_time"] = df[
    "avg_resolution_time"
].fillna(0)

df["avg_satisfaction"] = df[
    "avg_satisfaction"
].fillna(10)

In [23]:
df.head()

,user_id,country,industry,company_size,plan_type,monthly_revenue,is_churned,total_usage_events,avg_session_duration,total_tickets,avg_resolution_time,avg_satisfaction,total_campaign_engagements,email_open_rate,click_rate,customer_health_score,engagement_score,support_burden_score,marketing_engagement_score,frequency_score,monetary_score,recency_score
0,1,USA,SaaS,Enterprise,Pro,150,0,54,33.648148,0,0.000000,10.000000,15,0.666667,0.533333,49.459259,94.296296,0.000000,60.000000,54,150,3
1,2,India,Healthcare,Small,Basic,50,1,7,4.714286,3,69.333333,4.333333,2,0.000000,0.500000,10.885714,12.928571,20.333333,25.000000,7,50,20
2,3,UK,SaaS,Enterprise,Basic,50,1,13,5.230769,6,60.833333,3.666667,1,1.000000,0.000000,20.092308,16.961538,30.666667,50.000000,13,50,28
3,4,Canada,SaaS,Enterprise,Basic,50,0,99,34.747475,0,0.000000,10.000000,8,0.750000,0.750000,58.898990,118.994949,0.000000,75.000000,99,50,19
4,5,Germany,SaaS,Small,Basic,50,0,117,33.512821,4,16.250000,7.250000,11,0.545455,0.545455,38.132401,125.525641,17.500000,54.545455,117,50,13

In [25]:
df.select_dtypes(include=["object"]).columns

C:\Users\HP\AppData\Local\Temp\ipykernel_18096\2790643224.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.select_dtypes(include=["object"]).columns

Index(['country', 'industry', 'company_size', 'plan_type'], dtype='str')

In [26]:
df_encoded = pd.get_dummies(
    df,
    columns=[
        "country",
        "industry",
        "company_size",
        "plan_type"
    ],
    drop_first=True
)

In [27]:
df_encoded.head()

,user_id,monthly_revenue,is_churned,total_usage_events,avg_session_duration,total_tickets,avg_resolution_time,avg_satisfaction,total_campaign_engagements,email_open_rate,click_rate,customer_health_score,engagement_score,support_burden_score,marketing_engagement_score,frequency_score,monetary_score,recency_score,country_Germany,country_India,country_UK,country_USA,industry_Finance,industry_Healthcare,industry_Retail,industry_SaaS,company_size_Medium,company_size_Small,plan_type_Enterprise,plan_type_Pro
0,1,150,0,54,33.648148,0,0.000000,10.000000,15,0.666667,0.533333,49.459259,94.296296,0.000000,60.000000,54,150,3,False,False,False,True,False,False,False,True,False,False,False,True
1,2,50,1,7,4.714286,3,69.333333,4.333333,2,0.000000,0.500000,10.885714,12.928571,20.333333,25.000000,7,50,20,False,True,False,False,False,True,False,False,False,True,False,False
2,3,50,1,13,5.230769,6,60.833333,3.666667,1,1.000000,0.000000,20.092308,16.961538,30.666667,50.000000,13,50,28,False,False,True,False,False,False,False,True,False,False,False,False
3,4,50,0,99,34.747475,0,0.000000,10.000000,8,0.750000,0.750000,58.898990,118.994949,0.000000,75.000000,99,50,19,False,False,False,False,False,False,False,True,False,False,False,False
4,5,50,0,117,33.512821,4,16.250000,7.250000,11,0.545455,0.545455,38.132401,125.525641,17.500000,54.545455,117,50,13,True,False,False,False,False,False,False,True,False,True,False,False

In [28]:
from sklearn.preprocessing import StandardScaler

In [29]:
scaler = StandardScaler()

In [30]:
feature_cols = df_encoded.drop(
    columns=["is_churned"]
).columns

In [31]:
df_encoded[feature_cols] = scaler.fit_transform(
    df_encoded[feature_cols]
)

In [32]:
df_encoded.head()

,user_id,monthly_revenue,is_churned,total_usage_events,avg_session_duration,total_tickets,avg_resolution_time,avg_satisfaction,total_campaign_engagements,email_open_rate,click_rate,customer_health_score,engagement_score,support_burden_score,marketing_engagement_score,frequency_score,monetary_score,recency_score,country_Germany,country_India,country_UK,country_USA,industry_Finance,industry_Healthcare,industry_Retail,industry_SaaS,company_size_Medium,company_size_Small,plan_type_Enterprise,plan_type_Pro
0,-1.731704,0.176447,0,-0.217916,0.542815,-1.229930,-1.267584,1.358179,1.660340,8.978922e-07,0.248294,0.472755,0.244215,-1.343150,0.135435,-0.217916,0.176447,-1.462517,-0.516512,-0.506554,-0.480542,2.031798,-0.492175,-0.504371,-0.508112,1.976555,-0.70181,-0.712310,-0.338128,1.521004
1,-1.731012,-0.569631,1,-1.517139,-1.645210,-0.095518,1.370085,-0.929042,-1.438109,-2.228404e+00,0.130333,-1.115551,-1.663822,0.313283,-1.215766,-1.517139,-0.569631,0.572880,-0.516512,1.974123,-0.480542,-0.492175,-0.492175,1.982667,-0.508112,-0.505931,-0.70181,1.403882,-0.338128,-0.657461
2,-1.730319,-0.569631,1,-1.351280,-1.606152,1.038895,1.046717,-1.198127,-1.676452,1.114203e+00,-1.639082,-0.736460,-1.569251,1.155077,-0.250623,-1.351280,-0.569631,1.530714,-0.516512,-0.506554,2.080983,-0.492175,-0.492175,-0.504371,-0.508112,1.976555,-0.70181,-0.712310,-0.338128,-0.657461
3,-1.729626,-0.569631,0,1.026021,0.625948,-1.229930,-1.267584,1.358179,-0.008056,2.785515e-01,1.015040,0.861445,0.823388,-1.343150,0.714521,1.026021,-0.569631,0.453151,-0.516512,-0.506554,-0.480542,-0.492175,-0.492175,-0.504371,-0.508112,1.976555,-0.70181,-0.712310,-0.338128,-0.657461
4,-1.728933,-0.569631,0,1.523596,0.532581,0.282620,-0.649380,0.248204,0.706971,-4.051637e-01,0.291189,0.006360,0.976529,0.082469,-0.075142,1.523596,-0.569631,-0.265224,1.936063,-0.506554,-0.480542,-0.492175,-0.492175,-0.504371,-0.508112,1.976555,-0.70181,1.403882,-0.338128,-0.657461

In [33]:
df_encoded.shape

(5000, 30)

In [34]:
X = df_encoded.drop(
    columns=["is_churned"]
)

y = df_encoded["is_churned"]

In [35]:
X.head()

,user_id,monthly_revenue,total_usage_events,avg_session_duration,total_tickets,avg_resolution_time,avg_satisfaction,total_campaign_engagements,email_open_rate,click_rate,customer_health_score,engagement_score,support_burden_score,marketing_engagement_score,frequency_score,monetary_score,recency_score,country_Germany,country_India,country_UK,country_USA,industry_Finance,industry_Healthcare,industry_Retail,industry_SaaS,company_size_Medium,company_size_Small,plan_type_Enterprise,plan_type_Pro
0,-1.731704,0.176447,-0.217916,0.542815,-1.229930,-1.267584,1.358179,1.660340,8.978922e-07,0.248294,0.472755,0.244215,-1.343150,0.135435,-0.217916,0.176447,-1.462517,-0.516512,-0.506554,-0.480542,2.031798,-0.492175,-0.504371,-0.508112,1.976555,-0.70181,-0.712310,-0.338128,1.521004
1,-1.731012,-0.569631,-1.517139,-1.645210,-0.095518,1.370085,-0.929042,-1.438109,-2.228404e+00,0.130333,-1.115551,-1.663822,0.313283,-1.215766,-1.517139,-0.569631,0.572880,-0.516512,1.974123,-0.480542,-0.492175,-0.492175,1.982667,-0.508112,-0.505931,-0.70181,1.403882,-0.338128,-0.657461
2,-1.730319,-0.569631,-1.351280,-1.606152,1.038895,1.046717,-1.198127,-1.676452,1.114203e+00,-1.639082,-0.736460,-1.569251,1.155077,-0.250623,-1.351280,-0.569631,1.530714,-0.516512,-0.506554,2.080983,-0.492175,-0.492175,-0.504371,-0.508112,1.976555,-0.70181,-0.712310,-0.338128,-0.657461
3,-1.729626,-0.569631,1.026021,0.625948,-1.229930,-1.267584,1.358179,-0.008056,2.785515e-01,1.015040,0.861445,0.823388,-1.343150,0.714521,1.026021,-0.569631,0.453151,-0.516512,-0.506554,-0.480542,-0.492175,-0.492175,-0.504371,-0.508112,1.976555,-0.70181,-0.712310,-0.338128,-0.657461
4,-1.728933,-0.569631,1.523596,0.532581,0.282620,-0.649380,0.248204,0.706971,-4.051637e-01,0.291189,0.006360,0.976529,0.082469,-0.075142,1.523596,-0.569631,-0.265224,1.936063,-0.506554,-0.480542,-0.492175,-0.492175,-0.504371,-0.508112,1.976555,-0.70181,1.403882,-0.338128,-0.657461

In [36]:
y.head()

0    0
1    1
2    1
3    0
4    0
Name: is_churned, dtype: int64